# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '../.env'
end

platform :android do
  desc "Submit a new apk to the Github Releases"
  lane :'gh-apk-release' do
    current_version = "v" + flutter_version(pubspec_location: "pubspec.yaml")["version_name"] + "-build." + flutter_version(pubspec_location: "pubspec.yaml")["version_code"]

    git_commit(path: ["."], message: "build: " + current_version, skip_git_hooks: true)
    
    add_git_tag(tag: current_version)

    sh("git-chglog -o ../CHANGELOG.md --config ../.chglog/config.yml")

    release_notes = read_changelog(
      changelog_path: 'CHANGELOG.md',	# Specify path to CHANGELOG.md
      section_identifier: "[" +  current_version + "]",	# Specify what section to read
    )

    # flutter_bootstrap(
    #   flutter_channel: 'master',
    #   # Only do this when building for Android, otherwise we would enforce
    #   # existence of ANDROID_SDK_ROOT environment variable, which is completely
    #   # unnecessary when building for iOS.
    #   android_licenses: {
    #     'android-sdk-license' => '24333f8a63b6825ea9c5514f83c2829b004d1fee',
    #   },
    # ) 

    flutter_generate()

    output_file = flutter_build(
      build: 'apk',
    )

    github_release = set_github_release(
      repository_name: "justdigital/miccional-app",
      api_token: ENV["GITHUB_TOKEN"],
      name: current_version,
      tag_name: current_version,
      # description: (File.read("changelog") rescue "No changelog provided"),
      description: release_notes,
      commitish: "dev",
      is_prerelease: true,
      upload_assets: ["./build/app/outputs/flutter-apk/app-release.apk"]
      # upload_assets: ["./build/app/outputs/bundle/release/app-release.aab"]
    )

    # upload_to_play_store(
    #   track: "internal",
    #   aab:"./build/app/outputs/bundle/release/app-release.aab",
    #   version_code: flutter_version(pubspec_location: "pubspec.yaml")["version_code"]
    # )
  end
end
