# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '../.env'
end

platform :android do
  desc "Submit a new version to the Internal Tests"
  lane :internal do
    gradle(task: "clean", project_dir: "./android")

    flutter_generate()

    output_file = flutter_build(
      build: 'appbundle',
    )

    github_release = set_github_release(
      repository_name: "justdigital/miccional-app",
      api_token: ENV["GITHUB_TOKEN"],
      name: "v" + flutter_version(pubspec_location: "pubspec.yaml")["version_name"] + "-build." + flutter_version(pubspec_location: "pubspec.yaml")["version_code"],
      tag_name: flutter_version(pubspec_location: "pubspec.yaml")["version_name"] + "-build." + flutter_version(pubspec_location: "pubspec.yaml")["version_code"],
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "dev",
      is_prerelease: true,
      upload_assets: ["./build/app/outputs/bundle/release/app-release.aab"]
    )

    upload_to_play_store(
      track: "internal",
      aab:"./build/app/outputs/bundle/release/app-release.aab",
      version_code: flutter_version(pubspec_location: "pubspec.yaml")["version_code"]
    )
  end  

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
